apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dv-prod
  name: bot
  labels:
    app: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: cr.selcloud.ru/dv/bot-dv:latest
      imagePullSecrets:
        - name: my-registry-cred
