version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: no
    env_file:
      - .env
    networks:
      - app
    depends_on:
      - mongodb
    volumes:
      - ./bot:/usr/src/app/bot

  gradio:
    build:
      context: .
      dockerfile: ./site/Dockerfile
    restart: no
    networks:
      - app
    volumes:
      - ./site:/usr/src/app/site

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

networks:
  app:
    driver: bridge

volumes:
  dbdata6:
