version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: no
    env_file:
      - .env
    networks:
      - app
    volumes:
      - ./bot:/usr/src/app/bot

networks:
  app:
    driver: bridge
